name: publish-validation
run-name: Publish Validation

on:
  workflow_dispatch: {}
  push: {}

jobs:
  publish:
    runs-on: ${{ vars.RUNNER }}

    steps:
      - name: Echo
        run: echo "Published Validation Build."